export const FETCH_COACH_REQUEST = 'FETCH_COACH_REQUEST';
export const FETCH_COACH_SUCCESS = 'FETCH_COACH_SUCCESS';
export const FETCH_COACH_FAILURE = 'FETCH_COACH_FAILURE';

export const BOOK_SLOT_REQUEST = 'BOOK_SLOT_REQUEST';
export const BOOK_SLOT_SUCCESS = 'BOOK_SLOT_SUCCESS';
export const BOOK_SLOT_FAILURE = 'BOOK_SLOT_FAILURE';
