export const FETCH_COACH_REQUEST = 'FETCH_COACH_REQUEST';
export const FETCH_COACH_SUCCESS = 'FETCH_COACH_SUCCESS';
export const FETCH_COACH_FAILURE = 'FETCH_COACH_FAILURE';

export const PAY_SLOT_REQUEST = 'PAY_SLOT_REQUEST';
export const PAY_SLOT_SUCCESS = 'PAY_SLOT_SUCCESS';
export const PAY_SLOT_FAILURE = 'PAY_SLOT_FAILURE';
