export const FETCH_COMMENTS_REQUEST = 'FETCH_COMMENTS_REQUEST';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_FAILURE = 'FETCH_COMMENTS_FAILURE';

export const ADD_COMMENT_REQUEST = 'ADD_COMMENTS_REQUEST';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENTS_SUCCESS';
export const ADD_COMMENT_FAILURE = 'ADD_COMMENTS_FAILURE';
